In [2]:
pip install bs4

Collecting bs4
  Downloading bs4-0.0.2-py2.py3-none-any.whl.metadata (411 bytes)
Collecting beautifulsoup4 (from bs4)
  Downloading beautifulsoup4-4.15.0-py3-none-any.whl.metadata (3.8 kB)
Collecting soupsieve>=1.6.1 (from beautifulsoup4->bs4)
  Downloading soupsieve-3.0.4-py3-none-any.whl.metadata (4.4 kB)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\Users\nowre\AppData\Local\Programs\Python\Python314\Lib\site-packages (from beautifulsoup4->bs4) (4.15.0)
Downloading bs4-0.0.2-py2.py3-none-any.whl (1.2 kB)
Downloading beautifulsoup4-4.15.0-py3-none-any.whl (109 kB)
Downloading soupsieve-3.0.4-py3-none-any.whl (42 kB)
Installing collected packages: soupsieve, beautifulsoup4, bs4

   ------------- -------------------------- 1/3 [beautifulsoup4]
   ---------------------------------------- 3/3 [bs4]

Successfully installed beautifulsoup4-4.15.0 bs4-0.0.2 soupsieve-3.0.4
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.2.1 -> 26.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [14]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import csv
import re
import matplotlib.pyplot as plt
from urllib.parse import urljoin
import time

In [15]:
url = "https://www.keralauniversity.ac.in/affiliated-colleges"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers, timeout=30)

print(response.status_code)

soup = BeautifulSoup(response.text, "html.parser")

200

In [16]:
title = soup.find("title")

if title:
    print(title.text.strip())
else:
    print("Page title not found")

University of Kerala

In [17]:
headings = soup.find_all(["h1", "h2", "h3", "h4", "h5"])

print("Total headings:", len(headings))

for heading in headings:
    print(heading.text.strip())

Total headings: 207
University of Kerala
Affiliated Colleges
List of Affiliated Colleges in Alphabetic Order
A. J. College of Science and Technology, Thonnakkal
All Saints' College, Thiruvananthapuram
Allama Iqbal Institute of Management, Peringamala, Thiruvananthapuram
Ayyankali Memorial Arts and Science College, Kuryottumala, Vettithitta P. O., Pathanapuram
B.N.V. College of Teacher Education, Thiruvallam, Thiruvananthapuram
Baby John Memorial Govt. College, Chavara
Badhiriya B.Ed. Training College, Velichikkala, Kollam
Baselios Marthoma Mathews II Training College, Kottarakara
Bishop Jerome School of Architecture, Fathima College Road, Kollam
Bishop Jesudasan CSI Arts & Science College, Mulayara, Thiruvananthapuram
Bishop Moore College for the Hearing Impaired, Manakala, Adoor
Bishop Moore College, Mavelikkara, Alappuzha
Buddha College of Teacher Education, Cheppad, Muthukulam North, Alappuzha
C. H. M. M. College for Advanced Studies, Chavarcode, Varkala
Carmel College, Muhamma, Alappuzha
Christ College, Vizhinjam, Thiruvananthapuram
Christ Nagar Chavara Educational and Charitable Trust
Christ Nagar College of Education, Thiruvallam, Thiruvananthapuram
Christian College, Chengannur
Christian College, Kattakkada
Co-Operative Institute of Management and Technology, Manvila, Thiruvananthapuram
College of Applied Science (IHRD), Mavelikkara
College of Applied Science, Adoor
College of Applied Science, Kottarakkara
College of Applied Sciences (Managed by IHRD), Dhanuvachapuram
College of Applied Sciences (Managed by IHRD), Kalanjoor
College of Applied Sciences (Managed by IHRD), Karthikapally, Alappuzha
College of Applied Sciences (Managed by IHRD), Kundara, Kollam
College of Applied Sciences (Managed by IHRD), Perissery, Chengannur
College of Architecture, Thinavila, Mulayara, Thiruvananthapuram
College of Fine Arts, Thiruvananthapuram
College of Teacher Education, Arkannoor, Ayur, Kollam
CSI College of Education, Parassala
CSI Institute of Legal Studies, Cheruvarakonam, Thiruvananthapuram
DC School of Management and Technology, Kazhakoottam, Thiruvananthapuram
Divine Law College
Don Bosco College, Umayanalloor, Kottiyam
Dr. Palpu College of Arts and Science, Pangode, Puthussery, Kollam
Emmanuel College of  B.Ed. Training, Vazhichal, Thiruvananthapuram
Emmanuel College, Vazhichal, Thiruvananthapuram
Fathima Matha National College, Kollam
Fathima Memorial Training College, Mylapore, Umayanalloor, Kollam
Fathima Memorial Training College, Pallimukku, Vadakkevila, Kollam
G. Karunakaran Memorial Co-operative College of Management and Technology, Azhicode, TVM
Govt. Arts and Science College, Ambalapuzha
Govt. Arts and Science College, Kulathoor, Neyyattinkara
Govt. Arts and Science College, Thazhava, Karunagappally
Govt. Arts College, Thycaud, Thiruvananthapuram
Govt. College of Teacher Education, Thycaud, Thiruvananthapuram
Govt. College, Attingal
Govt. College, Kariavattom
Govt. College, Nedumangad
Govt. Kunjukrishnan Nadar Memorial Arts and Science College, Kanjiramkulam
Govt. Law College, Barton Hill, Thiruvananthapuram
Govt. Sanskrit College, Thiruvananthapuram
Grace International Academy, Punalur
Gregorian College of Advanced Studies, Sreekariyam, Thiruvananthapuram
Guru Nithya Chaithanya Yathi College Of Law and Research Centre
Gurudev Institute of Management Studies, Kadakkal, Kollam
H. H. The Maharaja's Govt. College for Women, Vazhuthacaud
H.H. Maharani Sethu Parvathi Bai N.S.S. College for Women, Neeramankara, Thiruvananthapuram
H.H. Marthoma Mathews II Training College, Adoor, Pathanamthitta
Haneefa Kunju Memorial College of Education, Umayanalloor, Kollam
IMDR College of Advanced Studies (I-CAS)
Institute of Fashion Technology, Kundara, Kollam
Institute of Land and Disaster Management
Institute of Management and Technology, Punnapra, Alappuzha
Iqbal college, Daivappura P.O, Peringammala, Thiruvananthapuram
Iqbal Training College, Peringammala, Thiruvananthapuram
Jameela Beevi Memorial Centre for Teacher Education, Kayamkulam, Alappuzha
Jamia Training College, Chithara, Kadakkal, Kollam
K.V.V.S. College of Science and Technology, Enathu, Adoor
Karmela Rani Training College, Fatima Road, Kollam
Kaviyattu College of Education, Pirappancode, Thiruvananthapuram
Kerala Institute of Co-Operative Management (KICMA), Neyyardam, Thiruvananthapuram
Kerala Institute of Tourism and Travel Management (KITTS), Thycaud, Thiruvananthapuram
KNM Arts & Science College, Kanjiramkulam, Thiruvananthapuram
KNMKNMS Training College, Vellarada, Thiruvananthapuram
KPM BEd. College, Cheriyavelinalloor, Oyoor, Kollam
KTCT College of Arts and Science, Kallambalam, Thiruvananthapuram
KTCT College of Teacher Education, Kaduvayil, Thottacadu, Thiruvananthapuram
Kumbalathu Sankupilla Memorial Devaswom Board College, Sasthamcottah
Kunjukrishnan Nadar Memorial B.Ed. College, Kanjiramkulam, Thiruvananthapuram
KVM College of Arts and Science, Kokkothamangalam, Cherthala
KVM College of Special Education, Cherthala, Alappuzha
KVVS Institute of Technology, Adoor, Pathanamthitta
Lakshmi bai National College of Physical Education (LNCPE), Kariavattom
Lourdes Matha College of Arts & Science Kuttichal, Thiruvananthapuram
Lourdes Matha Institute of Hotel Management and Catering Technology, Kuttichal, TVM
Loyola College of Social Sciences, Sreekariyam, Thiruvananthapuram
MAET Training College, Nettayam, Thiruvananthapuram
Mahatma Gandhi College, Thiruvananthapuram
Malayinkeezhu Madhavakavi Smaraka Govt. Arts and Science College, Malayinkeezhu
Manjappara Educational and Charitable Trust B.Ed Centre, Ayur, Kollam
Mannam Foundation Centre For Education Technology, Poruvazhy, Edakkad, Kollam
Mannam Memorial N.S.S. College, Kottiyam
Mannam Memorial Training College, Vilakudy, Kollam
Mannam NSS College, Edamulakkal, Anchal
Mannaniya College of Arts and Science, Pangode, Kallara
Mar Baselios Institute of Technology, Anchal, Kollam
Mar Chrysostom College, Paranthal, Adoor
Mar Gregorios Arts and Science College, Punnapra, Alappuzha
Mar Gregorios College of Law, Nalanchira, Thiruvananthapuram
Mar Ivanios College, Kallumala, Mavelikkara, Alappuzha
Mar Ivanios College, Nalanchira, Thiruvananthapuram
Mar Ivanios Law College
Mar Theophilus Training College, Nalanchira, Thiruvananthapuram
Marian College of Arts and Science, Menamkulam, Kazhakuttom
Marthoma College of Science and Technology, Ayur, Kollam
Marthoma Institute of Information Technology, Ayur, Kollam
Mater Dei CMI College, Enathu, Pathanamthitta
Member Sree Narayana Pillai Institute of Management and Technology, Mukundapuram, Chavara, Kollam
MES Arts and Science College
METCA Institute  of Teacher Education, Chavarcode, Thiruvananthapuram
MGM College of Arts & Science, Kadinamkulam, Thiruvananthapuram
Michaels Institute of Management Technology, Mayithara, Cherthala
Milad-E-Sherief Memorial College (MSM College), Kayamkulam
Millath College of Teacher Education, Kunnathur, Sooranadu, Kollam
Mother Theresa College, Nellikad, Kattakada
Mount Tabor Training College, Pathanapuram
MSN Institute of Management and Technology, Kollam
Muslim Association College of Arts & Science, Panavoor, Nedumangad
N.S.S. College, Cherthala
N.S.S. College, Nilamel
N.S.S. College, Pandalam
N.S.S. Training College, Pandalam
Naipunnya School of Management, Cherthala
Najeeth Royal College of Arts and Science
National College, Manacaud, Thiruvananthapuram
National Institute of Speech & Hearing (NISH), Akkulam, Thiruvananthapuram
National Training College for Women, Pazhakutty, Nedumangad
New B.Ed. College, Nellimoodu, Thiruvananthapuram
NSS Arts and Science College, Perayam, Kundara, Kollam
NSS Law College, Kottiyam, Kollam
Pattom Thanu Pillai Memorial College of Education, Balaramapuram, Thiruvananthapuram
Peet Memorial Training College, Mavelikkara
PMSA Pookoya Thangal Memorial Arts & Science College, Kadakkal, Kollam
Pushpageeth College of Teacher Education, Kottoor, Thiruvananthapuram
R. Parameswaran Pillai Memorial Arts and Science College, Neyyardam, Thiruvananthapuram
R. Sankar College of Arts & Science, Chathanoor, Kollam
Raja Ravi Varma College of Fine Arts, Mavelikara
Rama Vilasom Training College, Valakom, Kottarakkara, Kollam
Sabarigiri College of Education, Anchal, Kollam
Sanathana Dharma College, Alappuzha
Santhom Malankara Arts and Science College, Edanji, Trivandrum
Saraswathi College of Arts and Science, Vilappil
SDV College of Arts and Applied Sciences, Alappuzha
Silver Jubilee Law College
Snehacharya Institute of Management and Technology, Karuvatta, Alappuzha
Sobha College of Teacher Education, Mararikulam, Cherthala
Sree Ayyapa College, Thiruvanvandoor
Sree Narayana College for Women, Kollam
Sree Narayana College of Advanced Studies, Cherthala
Sree Narayana College of Technology, Vadakkevila, Kollam
Sree Narayana College, Chathannur
Sree Narayana College, Chempazhanthi
Sree Narayana College, Chengannur
Sree Narayana College, Cherthala
Sree Narayana College, Kollam
Sree Narayana College, Punalur
Sree Narayana College, Sivagiri, Varkala
Sree Narayana Guru College of Advanced Studies, Chempazhanthy
Sree Narayana Guru College of Advanced Studies, Nangiarkulangara
Sree Narayana Guru College of Advanced Studies, Punalur, Kollam
Sree Narayana Guru College of Advanced Studies, Sivagiri, Varkala
Sree Narayana Guru College of Legal Studies, Kollam
Sree Narayana Guru Kripa BEd College, Pothencode, Thiruvananthapuram
Sree Narayana Guru Memorial Arts and Science College, Thuravoor, Alappuzha
Sree Narayana Guru Memorial B.Ed College, Thuravur, Cherthala, Alappuzha
Sree Narayana Guru Memorial Catering College, Thuravoor, Cherthala
Sree Narayana Institute of Technology, Ezhamkulam
Sree Narayana Institute of Technology, Vadakkevila, Kollam
Sree Narayana Training College, Nedumganda, Varkala
Sree Narayana Training College, Poochackal, Sreekandeswaram, Cherthala
Sree Sankara College, Kilimanoor
Sree Sankara Vidyapeetom College, Nagaroor
Sree Sathya Sai Arts and Science College, Thonnakkal
Sree Vidyadhiraja College of Arts and Science, Karunagappally
Sri Swathi Thirunal College of Music, Thiruvananthapuram
Sri Vidyadhiraja Model College Of Teacher Education, Kottarakara, Kollam
St. Cyril's College, Adoor
St. Gregorios College, Kottarakkara
St. Jacob's Training College, Menamkulam, Kazhakuttom, Thiruvananthapuram
St. John's B.Ed Training College, Peringala, Kayamkulam, Alappuzha
St. John's College, Anchal
St. Joseph's College for Women, Alappuzha
St. Mary's College, Mulavana, Kundara, Kollam
St. Michael's College, Cherthala
St. Stephen's College, Pathanapuram
St. Thomas Training College, Mukkolakkal, Thiruvananthapuram
St. Tresa's College of Education, Kundara, Kollam
St. Xavier's College, Thumba, Trivandrum
T. K. Madhava Memorial College, Nangiarkulangara
T.K.M. College of Arts & Science, Kollam
Thangal Kunju Musaliar (TKM) Institute of Management, Kollam
The Kerala Law Academy Law College, Peroorkada, Thiruvananthapuram
Travancore Arts And Science College
University College Of Engineering
University College, Thiruvananthapuram
Valiyam Memorial College of Teacher Education, Chavara, Kollam
Victory College of Teacher Education, Olathanni, Neyyatinkara
Vigyaan College of Applied Sciences, Kattakode, Kattakada
VTM NSS College, Dhanuvachapuram
White Memorial College of Arts and Science , Panachamoodu, Vellarada

In [18]:
links = soup.find_all("a", href=True)

print("Total links:", len(links))

for link in links[:30]:
    print(link.text.strip(), "|", link["href"])

Total links: 574
University of Kerala | index.php
Home | index.php
About
              ▾
▾ | #
General
                  ▾
▾ | #
Grievance Redressal | grievance-redressal
A-Z index | a-z-index
Instrumentation Facility (CLIF) | http://kusicc.ac.in
Site map | site-map
Overview | our-history
University Act and Statutes | acts-statutes
Institutional Development Plan | /downloads/IDP_UOK_final_version.pdf
Recognition / Approval | recognition-approval
Annual Reports | annual-reports
NAAC | /NAAC
Institutional Data (NIRF) | nirf
QS Rankings | QS-ranking
ARIIA Report | ARIIA-Report
Annual Accounts | annual-accounts
Budget Estimate | budget-estimate
Vision & Mission | vision-mission
Founder | founder
Why KU? | why-ku
Facts and Figures | facts-figures
Administration
              ▾
▾ | #
Organogram Chart | #
Chancellor | chancellor
Pro-Chancellor | pro-chancellor
Vice Chancellor | vice-chancellor
Registrar | registrar
Finance Officer | finance-officer

In [20]:
college_headings = soup.find_all(["h3", "h4"])

for heading in college_headings[:20]:
    print("College:", heading.get_text(" ", strip=True))

    link = heading.find("a", href=True)

    if link:
        print("Website:", urljoin(url, link["href"]))

College: University of Kerala
College: Affiliated Colleges
College: A. J. College of Science and Technology, Thonnakkal
Website: http://www.ajcollege.in
College: All Saints' College, Thiruvananthapuram
Website: http://www.allsaintscollege.ac.in
College: Allama Iqbal Institute of Management, Peringamala, Thiruvananthapuram
Website: http://www.aimmba.com
College: Ayyankali Memorial Arts and Science College, Kuryottumala, Vettithitta P. O., Pathanapuram
Website: http://www.akmascollege.com
College: B.N.V. College of Teacher Education, Thiruvallam, Thiruvananthapuram
Website: http://www.bnvtrust.org
College: Baby John Memorial Govt. College, Chavara
Website: http://www.bjmgovtcollege.ac.in
College: Badhiriya B.Ed. Training College, Velichikkala, Kollam
Website: http://www.badhiriya.org
College: Baselios Marthoma Mathews II Training College, Kottarakara
Website: http://www.bmm2tc.org
College: Bishop Jerome School of Architecture, Fathima College Road, Kollam
College: Bishop Jesudasan CSI Arts & Science College, Mulayara, Thiruvananthapuram
Website: http://www.bjcsicollege.com
College: Bishop Moore College for the Hearing Impaired, Manakala, Adoor
College: Bishop Moore College, Mavelikkara, Alappuzha
Website: http://www.bishopmoorecollege.in
College: Buddha College of Teacher Education, Cheppad, Muthukulam North, Alappuzha
Website: http://bcte.in
College: C. H. M. M. College for Advanced Studies, Chavarcode, Varkala
Website: http://www.chmmcollege.edu.in
College: Carmel College, Muhamma, Alappuzha
Website: http://www.carmelcollegemuhamma.org
College: Christ College, Vizhinjam, Thiruvananthapuram
Website: http://www.christcollegevizhinjam.com
College: Christ Nagar Chavara Educational and Charitable Trust
Website: http://www.cnc.ac.in
College: Christ Nagar College of Education, Thiruvallam, Thiruvananthapuram
Website: http://www.christnagarcollege.org

In [21]:
college_data = []

college_headings = soup.find_all(["h3", "h4"])

for heading in college_headings:

    college_name = heading.get_text(" ", strip=True)

    if not college_name:
        continue

    college_website = ""
    email = ""
    phone = ""
    address = ""
    district = ""
    college_type = ""

    # Find the college's surrounding HTML section
    block = heading.parent

    for i in range(5):
        if block is None:
            break

        block_text = block.get_text(" ", strip=True)

        if "Estd." in block_text or "Self Financing" in block_text:
            break

        block = block.parent

    if block is None:
        block = heading.parent

    block_text = block.get_text(" ", strip=True)

    # Find links inside the college section
    block_links = block.find_all("a", href=True)

    for link in block_links:
        href = link["href"].strip()
        link_text = link.get_text(" ", strip=True)

        if href.startswith("mailto:") and not email:
            email = href.replace("mailto:", "").strip()

        elif href.startswith("tel:") and not phone:
            phone = href.replace("tel:", "").strip()

        elif href.startswith(("http://", "https://")):
            if "keralauniversity.ac.in" not in href.lower():
                if not college_website:
                    college_website = urljoin(url, href)

        elif href.startswith("www.") and not college_website:
            college_website = "https://" + href

    # Find an email address in the visible text
    if not email:
        email_match = re.search(
            r'[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}',
            block_text
        )

        if email_match:
            email = email_match.group()

    # Find a phone number in the visible text
    if not phone:
        phone_match = re.search(
            r'(?:\+91[\s-]?)?(?:0[\s-]?)?[6-9]\d{9}',
            block_text
        )

        if phone_match:
            phone = phone_match.group()

    # Extract district and college type from the listing text
    districts = [
        "Thiruvananthapuram",
        "Kollam",
        "Alappuzha",
        "Pathanamthitta"
    ]

    for d in districts:
        if d.lower() in block_text.lower():
            district = d
            break

    types = [
        "Government Self Financing",
        "Self Financing",
        "Government",
        "Aided",
        "Autonomous"
    ]

    for t in types:
        if t.lower() in block_text.lower():
            college_type = t
            break

    # Save the extracted information
    college_data.append({
        "College Name": college_name,
        "Address": address,
        "District": district,
        "College Type": college_type,
        "Contact Number": phone,
        "Email Address": email,
        "Website URL": college_website
    })

print("Records extracted:", len(college_data))

Records extracted: 206

In [22]:
df = pd.DataFrame(college_data)

df.head(10)

,College Name,Address,District,College Type,Contact Number,Email Address,Website URL
0,University of Kerala,,Thiruvananthapuram,Government Self Financing,,,http://www.ajcollege.in
1,Affiliated Colleges,,Thiruvananthapuram,Government Self Financing,,,http://www.ajcollege.in
2,"A. J. College of Science and Technology, Thonn...",,Thiruvananthapuram,Self Financing,,,http://www.ajcollege.in
3,"All Saints' College, Thiruvananthapuram",,Thiruvananthapuram,Aided,,,http://www.allsaintscollege.ac.in
4,"Allama Iqbal Institute of Management, Peringam...",,Thiruvananthapuram,Self Financing,,,http://www.aimmba.com
5,"Ayyankali Memorial Arts and Science College, K...",,Kollam,Aided,,,http://www.akmascollege.com
6,"B.N.V. College of Teacher Education, Thiruvall...",,Thiruvananthapuram,Self Financing,,,http://www.bnvtrust.org
7,"Baby John Memorial Govt. College, Chavara",,Kollam,Government,,,http://www.bjmgovtcollege.ac.in
8,"Badhiriya B.Ed. Training College, Velichikkala...",,Kollam,Self Financing,,,http://www.badhiriya.org
9,"Baselios Marthoma Mathews II Training College,...",,Kollam,Self Financing,,,http://www.bmm2tc.org

In [23]:
print("Dataset shape:", df.shape)

print("\nColumn names:")
print(df.columns)

print("\nDataset information:")
df.info()

Dataset shape: (206, 7)

Column names:
Index(['College Name', 'Address', 'District', 'College Type', 'Contact Number',
       'Email Address', 'Website URL'],
      dtype='object')

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 206 entries, 0 to 205
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   College Name    206 non-null    object
 1   Address         206 non-null    object
 2   District        206 non-null    object
 3   College Type    206 non-null    object
 4   Contact Number  206 non-null    object
 5   Email Address   206 non-null    object
 6   Website URL     206 non-null    object
dtypes: object(7)
memory usage: 11.4+ KB

In [24]:
print("Missing values in each column:")

print(df.isnull().sum())

print("\nEmpty values in each column:")

print((df == "").sum())

Missing values in each column:
College Name      0
Address           0
District          0
College Type      0
Contact Number    0
Email Address     0
Website URL       0
dtype: int64

Empty values in each column:
College Name        0
Address           206
District            0
College Type        1
Contact Number    206
Email Address     206
Website URL        31
dtype: int64

In [25]:
print("Rows before removing duplicates:", len(df))

df = df.drop_duplicates(subset=["College Name"])

df = df.reset_index(drop=True)

print("Rows after removing duplicates:", len(df))

Rows before removing duplicates: 206
Rows after removing duplicates: 206

In [26]:
for column in df.columns:
    df[column] = df[column].fillna("").astype(str).str.strip()

df["College Name"] = df["College Name"].str.replace(
    r"\s+", " ", regex=True
)

df.head()

,College Name,Address,District,College Type,Contact Number,Email Address,Website URL
0,University of Kerala,,Thiruvananthapuram,Government Self Financing,,,http://www.ajcollege.in
1,Affiliated Colleges,,Thiruvananthapuram,Government Self Financing,,,http://www.ajcollege.in
2,"A. J. College of Science and Technology, Thonn...",,Thiruvananthapuram,Self Financing,,,http://www.ajcollege.in
3,"All Saints' College, Thiruvananthapuram",,Thiruvananthapuram,Aided,,,http://www.allsaintscollege.ac.in
4,"Allama Iqbal Institute of Management, Peringam...",,Thiruvananthapuram,Self Financing,,,http://www.aimmba.com

In [27]:
def valid_email(email):
    pattern = r'^[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}$'
    return bool(re.match(pattern, email))

df["Email Valid"] = df["Email Address"].apply(
    lambda email: valid_email(email) if email else False
)

print("Valid emails:", df["Email Valid"].sum())

print("Invalid or missing emails:", (~df["Email Valid"]).sum())

Valid emails: 0
Invalid or missing emails: 206

In [28]:
def valid_phone(phone):
    digits = re.sub(r"\D", "", phone)

    if digits.startswith("91") and len(digits) == 12:
        digits = digits[2:]

    return len(digits) == 10 and digits[0] in "6789"

df["Phone Valid"] = df["Contact Number"].apply(
    lambda phone: valid_phone(phone) if phone else False
)

print("Valid phone numbers:", df["Phone Valid"].sum())

print("Invalid or missing phone numbers:", (~df["Phone Valid"]).sum())

Valid phone numbers: 0
Invalid or missing phone numbers: 206

In [29]:
print("Total colleges:", len(df))

print(
    "Colleges with missing email:",
    (df["Email Address"] == "").sum()
)

print(
    "Colleges with missing website:",
    (df["Website URL"] == "").sum()
)

print(
    "Colleges with missing phone:",
    (df["Contact Number"] == "").sum()
)

print(
    "Unique districts:",
    df.loc[df["District"] != "", "District"].nunique()
)

Total colleges: 206
Colleges with missing email: 206
Colleges with missing website: 31
Colleges with missing phone: 206
Unique districts: 4

In [30]:
df.to_csv(
    "kerala_university_colleges.csv",
    index=False,
    encoding="utf-8-sig"
)

print("CSV file saved successfully")

CSV file saved successfully